[package]
name = "otp-rpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "otp_rpy"
crate-type = ["cdylib"]

[dependencies]
base32 = "0.5.1"
hmac = "0.12.1"
pyo3 = "0.24.0"
sha1 = "0.10.6"
